create  table customers (
                            id bigint generated by default as identity,
                            customer_id varchar(255),
                            name varchar(255),
                            status smallint,
                            primary key (id)
);

insert into customers (customer_id, name, status) values
    ('111', 'Top one percent', 1);

