# this workflow will be triggered when
#
#  1. a pull request is raised
#  2. a push to 'develop' branch takes place
#  3. a release tag is created on the repo
#
# a maven build and test will be performed when the action is triggered. for 2 and 3, a container image will be created
# and pushed to Github Container Resitry. The following tagging logic will be applied:
#
#  for push to develop branch, develop-YYYYMMDD-HHMISS-SHA7. the tagging should be sortable by chronological order so that
#  it can be picked up by CD tools, e.g. FluxCD, for updating the deployment automatically
#
#  for push to main xxx (not yet implemented)
#  for new tag, the image tag will be same as the repository tag (not yet implemented)

on:
  push:
    branches:
    - develop
    - feature/*

    tags:
    - rel-**

  pull_request:
    types: [opened, edited, reopened]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and test Java code
      run: mvn --batch-mode -s settings.xml clean test
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: set image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,suffix=-{{sha}},event=tag
          type=raw,value=develop-{{date 'YYYYMMDD-HHmmss' tz='Asia/Singapore'}}-{{sha}},enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
        flavor: |
          latest=false
        labels: |
          org.opencontainers.image.source https://github.com/{{ ${{ github.repository }}

    - name: Login to github registry
      if: steps.meta.outputs.tags != ''
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and push container image
      if: steps.tagging.outputs.tags != ''
      run: mvn --batch-mode -s settings.xml jib:build -DskipTests -Djib.to.image="ghcr.io/${{ github.repository }}" -Djib.to.tags="${{ steps.meta.outputs.tags }}" -Djib.container.labels="${{ steps.meta.outputs.labels }}"
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}