# name: run pytest to test code generations

on:
  push:
    branches:
      - main
      - develop
      - feature/*

  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  python-test-and-build-image:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install Python using uv ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build generate Maven projects
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          uv run pytest -v
        env:
          SKIP_MAVEN_TEST: "N"
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
